version: '2.3'
services:
  nginx:
    image: labhackercd/nginx-edemocracia
    depends_on:
      - colab
    volumes:
      - colab_assets:/var/labhacker/colab/public:z
      - audiencias:/var/labhacker/audiencias:z
      - wikilegis:/var/labhacker/wikilegis:z
    ports:
      - "8000:80"
    links:
      - 'audienciasweb'
    environment:
      NAME_RESOLVER: '127.0.0.11'

  db:
    image: postgres
    healthcheck:
      test: runuser postgres -c "pg_isready"
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
      PGDATA : /var/lib/postgresql/data/
    volumes:
      - colab_data:/var/lib/postgresql/data/

  colab:
    image: labhackercd/edemocracia-colab
    command: ./start-colab.sh
    environment:
      DEBUG: 'True'
      TEMPLATE_DEBUG: 'True'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia" <edemocracia@camara.leg.br>'
      SERVER_EMAIL: ''
      EMAIL_HOST: ''
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_TLS: ''
      EMAIL_SUBJECT_PREFIX: '[e-Democracia]'
      SECRET_KEY: 'secret'
      ALLOWED_HOSTS: '*'
      ROBOTS_NOINDEX: "True"
      SOCIAL_AUTH_GOOGLE_OAUTH2_KEY: ''
      SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET: ''
      SOCIAL_AUTH_FACEBOOK_KEY: ''
      SOCIAL_AUTH_FACEBOOK_SECRET: ''
      DATABASE_HOST: 'db'
      DATABASE_NAME: 'colab'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
      MEMCACHED_LOCATION: 'memcached:1234'
      ADMIN_EMAIL: email@admin.com
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: 123
      SITE_DOMAIN: http://127.0.0.1:8000
      SITE_NAME: Câmara dos Deputados
      SITE_LOGO: ''
      SITE_BACKGROUND_IMAGE: ''
      ENABLE_AUDIENCIAS: 'true'
      ENABLE_WIKILEGIS: 'true'
      AUDIENCIAS_API_KEY: secret_key
      WIKILEGIS_API_KEY: api_key
    volumes:
      - colab_assets:/var/labhacker/colab/public:z
    links:
      - 'audienciasweb'
    expose:
      - "8000"
    depends_on:
      - db

  redis:
    image: redis:alpine
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5

  audienciasweb:
    image: labhackercd/audiencias-publicas
    command: ./start-web.sh
    restart: on-failure
    links:
      - db
      - redis
    volumes:
      - audiencias:/var/labhacker/audiencias
    environment:
      EMAIL_HOST: ''
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_PORT: 25
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[audiencias]" <edemocracia@camara.leg.br>'
      NOTIFICATION_EMAIL_LIST: edemocracia@camara.leg.br,portalconteudo.lista@camara.leg.br
      DJANGO_SECRET_KEY: secret_key
      DEBUG: 'False'
      ENABLE_REMOTE_USER: 'True'
      URL_PREFIX: audiencias
      FORCE_SCRIPT_NAME: /audiencias
      STATIC_URL: /audiencias/static/
      SESSION_COOKIE_NAME: audiencias_session
      LOGIN_URL: /home
      LOGIN_REDIRECT_URL: /home
      LOGOUT_REDIRECT_URL: /home
      ALLOWED_HOSTS: 'audienciasweb, 127.0.0.1'
      YOUTUBE_API_KEY: ''
      YOUTUBE_CHANNEL_ID: ''
      YOUTUBE_SEARCH_QUERY: ''
      GOOGLE_ANALYTICS_ID: ''
      OLARK_ID: ''
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: email@admin.com
      ADMIN_USERNAME: admin
      DATABASE_URL: postgres://root:root@db:5432/audiencias
      DEBUG: 'False'
      REDIS_SERVER: redis
      WEBSERVICE_URL: https://infoleg.camara.leg.br/ws-pauta/evento/interativo
      COMPRESS_OFFLINE: 'True'
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  audienciasworker:
    image: labhackercd/audiencias-publicas
    command: ./start-worker.sh
    links:
      - redis
      - db
    environment:
      EMAIL_HOST: ''
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_PORT: 25
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[audiencias]" <edemocracia@camara.leg.br>'
      NOTIFICATION_EMAIL_LIST: edemocracia@camara.leg.br,portalconteudo.lista@camara.leg.br
      DJANGO_SECRET_KEY: secret_key
      DEBUG: 'False'
      ENABLE_REMOTE_USER: 'True'
      URL_PREFIX: audiencias
      FORCE_SCRIPT_NAME: /audiencias
      STATIC_URL: /audiencias/static/
      SESSION_COOKIE_NAME: audiencias_session
      LOGIN_URL: /home
      LOGIN_REDIRECT_URL: /home
      LOGOUT_REDIRECT_URL: /home
      ALLOWED_HOSTS: 'audienciasweb, 127.0.0.1'
      YOUTUBE_API_KEY: ''
      YOUTUBE_CHANNEL_ID: ''
      YOUTUBE_SEARCH_QUERY: ''
      GOOGLE_ANALYTICS_ID: ''
      OLARK_ID: ''
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: email@admin.com
      ADMIN_USERNAME: admin
      DATABASE_URL: postgres://root:root@db:5432/audiencias
      DEBUG: 'False'
      REDIS_SERVER: redis
      WEBSERVICE_URL: https://infoleg.camara.leg.br/ws-pauta/evento/interativo
      COMPRESS_OFFLINE: 'True'
    volumes:
      - audiencias:/var/labhacker/audiencias
    depends_on:
      - 'audienciasweb'

  wikilegisweb:
    image: labhackercd/wikilegis:1.3.0
    command: ./start.sh
    restart: on-failure
    links:
      - db
    volumes:
      - wikilegis:/var/labhacker/wikilegis
    environment:
      API_KEY: api_key
      SECRET_KEY: secret_key
      FORCE_SCRIPT_NAME: /wikilegis
      DEBUG: 'False'
      ALLOWED_HOSTS: '*'
      LOGIN_URL: /home
      LOGIN_REDIRECT_URL: /
      AUTH_USER_MODEL: accounts.User
      ENABLE_REMOTE_USER: 'True'
      SESSION_COOKIE_NAME: wikilegis_session
      ACCOUNT_ACTIVATION_REQUIRED: 0
      ACCOUNT_ACTIVATION_DAYS: 7
      ENABLE_SOCIAL_AUTH: 'False'
      EMAIL_HOST: ''
      EMAIL_PORT: 25
      EMAIL_HOST_USER: ''
      EMAIL_HOST_PASSWORD: ''
      EMAIL_USE_TLS: 'False'
      DEFAULT_FROM_EMAIL: '"Portal e-Democracia[Wikilegis]" <edemocracia@camara.leg.br>'
      LANGUAGE_CODE: pt-br
      TIME_ZONE: America/Sao_Paulo
      STATIC_URL: /wikilegis/static/
      MEDIA_URL: /wikilegis/media/
      COMPRESS_OFFLINE: 'True'
      ADMIN_PASSWORD: 123
      ADMIN_EMAIL: email@admin.com
      DATABASE_ENGINE: postgresql_psycopg2
      DATABASE_NAME: wikilegis
      DATABASE_PASSWORD: root
      DATABASE_USER: root
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DEBUG: 'False'
    expose:
      - "8000"
    depends_on:
      - db

volumes:
  colab_data:
    driver: local
  colab_assets:
    driver: local
  audiencias:
    driver: local
  wikilegis:
    driver: local